version: 2
jobs:
  build:
    working_directory: ~/workspace
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.2
        restart: on-failure # Restart the container if it exits due to an error
    steps:
      - checkout
      - run: dotnet restore
      - run: dotnet build -c Release --version-suffix $CIRCLE_BUILD_NUM --runtime ubuntu.18.10-x64
      - run: dotnet publish -c Release
      - setup_remote_docker:
          docker_layer_caching: true
      # use a primary image that already has Docker (recommended)
      # or install it during a build like we do here
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - run:
          name: "Build & Push docker image"
          command: |
            VERSION=v$CIRCLE_BUILD_NUM
            docker build -t khteh/twitteroauth.asp.netcore:latest .
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker push khteh/twitteroauth.asp.netcore:latest