version: 2
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.2
    steps:
      - checkout
      - run: dotnet restore
      - run: dotnet build
      - run: dotnet publish -c Release
      - run: docker build -t khteh/twitteroauth.asp.netcore:latest .
      - run: docker push khteh/twitteroauth.asp.netcore:latest